name: Node.js Package

on:
  pull_request:
    branches:
      - feat/add-npm-publish
  push:
    branches:
      - feat/add-npm-publish
#  release:
#    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install nodejs dependencies
        run: sudo apt-get install gpg dirmngr

      - name: Install nodejs
        uses: asdf-vm/actions/install@v1.0.0
        before_install: bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring

      - run: |
          npm init --scope=@kollegorna
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
